# For local docker setup, see docker-compose.local.yml
# For production docker setup, see docker-compose.prod.yml

version: "3.9"

services:
  api:
    container_name: shopkeepers-quiz-api
    depends_on:
      - mongodb
      - seq

  mongodb:
    container_name: shopkeepers-quiz-mongodb
    image: mongo:latest

  seq:
    container_name: shopkeepers-quiz-logs
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
