name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    environment:
      name: production
      url: https://api.shopkeepersquiz.com

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINERREGISTRYACCESSTOKEN }}

      - name: Setup SSH key & host
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          ssh-host: ${{ secrets.DEPLOYMENT_HOST }}

      - name: Deploy with Docker Compose
        env:
          VERSION: ${{ github.event.inputs.version }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        run: |
          docker context create deploy --docker "host=ssh://${{ secrets.DEPLOYMENT_SSH_USER }}@${{ secrets.DEPLOYMENT_HOST }}"
          docker context use deploy
          docker image prune -af
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull -q
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d